specVersion: 0.2.0
name: stafi-dao-query
version: 1.0.0
description: 'stafi-dao-query'
repository: 'https://github.com/makefriendwithtime/stafi-dao-query'
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x91bc6e169807aaa54802737e1c504b2577d4fafedd5a02c10293b1cd60e39527'
  endpoint: wss://moonbeam-alpha.api.onfinality.io/public-ws
  dictionary: 'https://api.subquery.network/sq/subquery/moonbase-alpha-dictionary'
#  genesisHash: '0x401a1f9dca3da46f5c4091016c8a2f26dcea05865116b286f60f668207d1474b' # Genesis hash of Moonriver
#  endpoint: wss://moonriver.api.onfinality.io/public-ws
#  dictionary: 'https://api.subquery.network/sq/subquery/moonriver-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/FrontierEvm
    startBlock: 2129700
    processor:
      file: './node_modules/@subql/contract-processors/dist/frontierEvm.js'
      options:
        abi: governance
        address: '0x3F8bc5F0D5c92820d8aF60D98e63efDef55804D3'
    assets:
      governance:
        file: './abi.governance.json'
    mapping:
      file: './dist/index.js'
      handlers:
        - handler: handleGovernEvmEvent
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - StartGovern(address indexed creator,uint256 number,uint256 governType,uint256 startDate,uint256 endDate,uint256 uintValue,string strValue,uint256 totalVoter)
        - handler: handleVoteEvmEvent
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - VoteByNumber(address indexed votor,uint256 number,uint256 governType,uint256 state,uint256 voters)