<template>
  <div class="sub">
    <div class="stit" style="padding: 50px 0px">WHAT IS</div>
    <div class="scot" style="min-height: 500px">
      <div class="content">
        Stafi DAO is a highly autonomous multi-chain community.<br />
        Community users are divided into: pledge users, lease users and
        technical service providers. <br />
        Pledge function: establish a swap trading pool of stkToken to solve the
        problem of depletion of liquidity for DAO Pool redemption; pledge users
        provide liquid collateral for DAO Pool, and users pledge native Token to
        obtain stkToken, a certificate for redeeming the pledge; community users
        Initiate proposals for governance and automatically change Pool
        operating parameters to achieve decentralized community autonomy; Pledge
        user income: Hold stkToken to get airdrop reward retToken (used for
        leasing pledge), and get node pledge reward generated by leasing;
        Leasing function: establish a swap transaction pool of retToken to solve
        the problem of demand circulation; The lease user obtains retToken from
        the transaction pool, sets the lease time, burns the retToken and
        mortgages part of the retToken to lease the pledge from the DAO Pool and
        pledge it to the Pos node; Leasing user income: Collectors (validators)
        receive node technology fees for node pledge rewards, and delegators
        receive node pledge rewards; The technical service provider provides
        technical support and upgrade services for the DAO community; Technical
        service provider's income: get technical service fees. The positioning
        of DAO is clear and the users are clear. With the healthy operation of
        the Pool, it will definitely bring better governance, more income and
        higher liquidity to the three-party users in the community.<br />
        Moonbeam related ecology used in the project: Use zenlink dex as a
        liquidity trading pool for stkToken and retToken; Use subquery as a data
        layer for query governance, voting, airdrops and rewards.
      </div>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {};
  },
};
</script>

<style>
</style>
